-- Chạy bằng tài khoản có quyền DBA/SYS trước khi chạy schema.
-- Script idempotent: có thể chạy lại nếu user GAME_PLATFORM đã tồn tại.

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM dba_users
    WHERE username = 'GAME_PLATFORM';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE USER GAME_PLATFORM IDENTIFIED BY game123
                DEFAULT TABLESPACE USERS
                TEMPORARY TABLESPACE TEMP
                QUOTA UNLIMITED ON USERS
        ]';
    END IF;
END;
/

GRANT CREATE SESSION TO GAME_PLATFORM;
GRANT CREATE TABLE TO GAME_PLATFORM;
GRANT CREATE VIEW TO GAME_PLATFORM;
GRANT CREATE SEQUENCE TO GAME_PLATFORM;
GRANT CREATE TRIGGER TO GAME_PLATFORM;
GRANT CREATE PROCEDURE TO GAME_PLATFORM;
