-- Tạo sequence sinh khóa chính
-- File tách riêng để dễ trình bày phần HQTCSDL.

CREATE SEQUENCE SEQ_TaiKhoan START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NhanVien START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NhaPhatTrien START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NguoiChoi START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TheLoai START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_Game START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GameMedia START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PhienBanGame START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_YeuCauPhatHanh START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GiaoDich START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DanhGia START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_KhuyenMai START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MaGiamGia START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_Ticket START WITH 1000 INCREMENT BY 1 NOCACHE;


