-- Tạo bảng dữ liệu, chưa gắn ràng buộc
-- File tách riêng để dễ trình bày phần HQTCSDL.

CREATE TABLE TaiKhoan (
    MaTaiKhoan NUMBER DEFAULT SEQ_TaiKhoan.NEXTVAL,
    TenDangNhap VARCHAR2(50 CHAR) NOT NULL,
    MatKhau VARCHAR2(255 CHAR) NOT NULL,
    LoaiTaiKhoan VARCHAR2(30 CHAR) NOT NULL,
    TrangThai VARCHAR2(30 CHAR) DEFAULT 'Đang hoạt động' NOT NULL,
    NgayTao DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE NhanVien (
    MaNV NUMBER DEFAULT SEQ_NhanVien.NEXTVAL,
    MaTaiKhoan NUMBER NOT NULL,
    HoTen VARCHAR2(100 CHAR) NOT NULL,
    VaiTro VARCHAR2(50 CHAR) NOT NULL,
    Email VARCHAR2(100 CHAR) NOT NULL,
    SDT VARCHAR2(15 CHAR)
);

CREATE TABLE NhaPhatTrien (
    MaNPT NUMBER DEFAULT SEQ_NhaPhatTrien.NEXTVAL,
    MaTaiKhoan NUMBER NOT NULL,
    TenNPT VARCHAR2(100 CHAR) NOT NULL,
    LoaiNPT VARCHAR2(30 CHAR) NOT NULL,
    Email VARCHAR2(100 CHAR) NOT NULL,
    SDT VARCHAR2(15 CHAR),
    DiaChi VARCHAR2(200 CHAR),
    TyLeChiaSe NUMBER(4,2) DEFAULT 0.70 NOT NULL
);

CREATE TABLE NguoiChoi (
    MaNguoiChoi NUMBER DEFAULT SEQ_NguoiChoi.NEXTVAL,
    MaTaiKhoan NUMBER NOT NULL,
    TenHienThi VARCHAR2(100 CHAR) NOT NULL,
    NgaySinh DATE NOT NULL,
    Email VARCHAR2(100 CHAR) NOT NULL,
    SDT VARCHAR2(15 CHAR),
    QuocGia VARCHAR2(50 CHAR)
);

CREATE TABLE TheLoai (
    MaTheLoai NUMBER DEFAULT SEQ_TheLoai.NEXTVAL,
    TenTheLoai VARCHAR2(100 CHAR) NOT NULL,
    MoTa VARCHAR2(500 CHAR)
);

CREATE TABLE Game (
    MaGame NUMBER DEFAULT SEQ_Game.NEXTVAL,
    MaNPT NUMBER NOT NULL,
    TenGame VARCHAR2(150 CHAR) NOT NULL,
    DoTuoi NUMBER(2) DEFAULT 0 NOT NULL,
    GiaGoc NUMBER(12,2) DEFAULT 0 NOT NULL,
    TrangThai VARCHAR2(30 CHAR) DEFAULT 'Chưa phát hành' NOT NULL,
    NgayPhatHanh DATE,
    LuotMua NUMBER DEFAULT 0 NOT NULL,
    MoTa VARCHAR2(1000 CHAR)
);

CREATE TABLE GameMedia (
    MaMedia NUMBER DEFAULT SEQ_GameMedia.NEXTVAL,
    MaGame NUMBER NOT NULL,
    LoaiMedia VARCHAR2(30 CHAR) NOT NULL,
    FileMedia VARCHAR2(255 CHAR) NOT NULL
);

CREATE TABLE DanhMucTheLoai (
    MaTheLoai NUMBER NOT NULL,
    MaGame NUMBER NOT NULL
);

CREATE TABLE PhienBanGame (
    MaPhienBan NUMBER DEFAULT SEQ_PhienBanGame.NEXTVAL,
    MaGame NUMBER NOT NULL,
    TenPhienBan VARCHAR2(100 CHAR) NOT NULL,
    NoiDungPhienBan VARCHAR2(1000 CHAR),
    FilePhienBan VARCHAR2(255 CHAR),
    DungLuong NUMBER(12,2) NOT NULL,
    NgayTao DATE DEFAULT SYSDATE NOT NULL,
    TrangThai VARCHAR2(30 CHAR) DEFAULT 'Chưa phát hành' NOT NULL
);

CREATE TABLE YeuCauPhatHanh (
    MaYeuCau NUMBER DEFAULT SEQ_YeuCauPhatHanh.NEXTVAL,
    MaNPT NUMBER NOT NULL,
    MaGame NUMBER NOT NULL,
    MaPhienBan NUMBER,
    NgayYeuCau DATE DEFAULT SYSDATE NOT NULL,
    TrangThai VARCHAR2(30 CHAR) DEFAULT 'Chờ duyệt' NOT NULL,
    MaNVXuLy NUMBER,
    LyDoTuChoi VARCHAR2(500 CHAR),
    NgayXuLy DATE
);

CREATE TABLE Wishlist (
    MaNguoiChoi NUMBER NOT NULL,
    MaGame NUMBER NOT NULL,
    NgayThem DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE GioHang (
    MaNguoiChoi NUMBER NOT NULL,
    MaGame NUMBER NOT NULL,
    NgayThem DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE MaGiamGia (
    MaMaGiamGia NUMBER DEFAULT SEQ_MaGiamGia.NEXTVAL,
    Code VARCHAR2(50 CHAR) NOT NULL,
    SoTienGiam NUMBER(12,2) DEFAULT 0 NOT NULL,
    GioiHanSuDung NUMBER DEFAULT 0 NOT NULL,
    LuotDung NUMBER DEFAULT 0 NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayHetHan DATE NOT NULL,
    TongGiaToiThieu NUMBER(12,2) DEFAULT 0 NOT NULL,
    TrangThai VARCHAR2(30 CHAR) DEFAULT 'Đang hiệu lực' NOT NULL,
    MoTa VARCHAR2(500 CHAR)
);

CREATE TABLE GiaoDich (
    MaGD NUMBER DEFAULT SEQ_GiaoDich.NEXTVAL,
    MaNguoiChoi NUMBER NOT NULL,
    MaMaGiamGia NUMBER,
    TongTienGoc NUMBER(12,2) DEFAULT 0 NOT NULL,
    TongGiamGia NUMBER(12,2) DEFAULT 0 NOT NULL,
    TongThanhToan NUMBER(12,2) DEFAULT 0 NOT NULL,
    PhuongThucThanhToan VARCHAR2(50 CHAR) NOT NULL,
    NgayGD DATE DEFAULT SYSDATE NOT NULL,
    TrangThai VARCHAR2(30 CHAR) DEFAULT 'Chờ thanh toán' NOT NULL
);

CREATE TABLE ChiTietGiaoDich (
    MaGD NUMBER NOT NULL,
    MaGame NUMBER NOT NULL,
    GiaGoc NUMBER(12,2) NOT NULL,
    SoTienGiamKM NUMBER(12,2) DEFAULT 0 NOT NULL,
    GiaBan NUMBER(12,2) NOT NULL
);

CREATE TABLE SoHuuGame (
    MaNguoiChoi NUMBER NOT NULL,
    MaGame NUMBER NOT NULL,
    MaGD NUMBER NOT NULL,
    NgaySoHuu DATE DEFAULT SYSDATE NOT NULL,
    SoGioChoi NUMBER DEFAULT 0 NOT NULL,
    ThanhTuuDatDuoc VARCHAR2(500 CHAR)
);

CREATE TABLE DanhGia (
    MaDanhGia NUMBER DEFAULT SEQ_DanhGia.NEXTVAL,
    MaGame NUMBER NOT NULL,
    MaNguoiChoi NUMBER NOT NULL,
    DiemDanhGia NUMBER(1) NOT NULL,
    NoiDung VARCHAR2(1000 CHAR),
    NgayDanhGia DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE KhuyenMai (
    MaKM NUMBER DEFAULT SEQ_KhuyenMai.NEXTVAL,
    TenKM VARCHAR2(150 CHAR) NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL,
    TrangThai VARCHAR2(30 CHAR) DEFAULT 'Đang hiệu lực' NOT NULL,
    NoiDung VARCHAR2(1000 CHAR)
);

CREATE TABLE ChiTietKhuyenMai (
    MaKM NUMBER NOT NULL,
    MaGame NUMBER NOT NULL,
    PhanTramKM NUMBER(5,2) NOT NULL
);

CREATE TABLE Ticket (
    MaTicket NUMBER DEFAULT SEQ_Ticket.NEXTVAL,
    LoaiYeuCau VARCHAR2(50 CHAR) NOT NULL,
    NoiDung VARCHAR2(1000 CHAR) NOT NULL,
    MaNguoiChoi NUMBER NOT NULL,
    MaGame NUMBER,
    MaGD NUMBER,
    NgayTao DATE DEFAULT SYSDATE NOT NULL,
    TrangThai VARCHAR2(30 CHAR) DEFAULT 'Chờ xử lý' NOT NULL,
    MaNVXuLy NUMBER,
    NoiDungPhanHoi VARCHAR2(1000 CHAR),
    NgayXuLy DATE
);


