-- Gắn khóa chính, khóa ngoại, unique, check và index nghiệp vụ
-- File tách riêng để dễ trình bày phần HQTCSDL.

ALTER TABLE TaiKhoan ADD CONSTRAINT PK_TaiKhoan PRIMARY KEY (MaTaiKhoan);
ALTER TABLE TaiKhoan ADD CONSTRAINT UQ_TaiKhoan_TenDangNhap UNIQUE (TenDangNhap);
ALTER TABLE TaiKhoan ADD CONSTRAINT CK_TaiKhoan_Loai CHECK (LoaiTaiKhoan IN ('Người chơi', 'Nhà phát triển', 'Nhân viên'));
ALTER TABLE TaiKhoan ADD CONSTRAINT CK_TaiKhoan_TrangThai CHECK (TrangThai IN ('Đang hoạt động', 'Ngưng hoạt động', 'Bị khóa'));
ALTER TABLE NhanVien ADD CONSTRAINT PK_NhanVien PRIMARY KEY (MaNV);
ALTER TABLE NhanVien ADD CONSTRAINT UQ_NhanVien_TaiKhoan UNIQUE (MaTaiKhoan);
ALTER TABLE NhanVien ADD CONSTRAINT UQ_NhanVien_Email UNIQUE (Email);
ALTER TABLE NhanVien ADD CONSTRAINT CK_NhanVien_VaiTro CHECK (VaiTro IN ('Quản lý nền tảng', 'Kiểm duyệt viên', 'Marketing', 'CSKH'));
ALTER TABLE NhanVien ADD CONSTRAINT FK_NhanVien_TaiKhoan FOREIGN KEY (MaTaiKhoan) REFERENCES TaiKhoan(MaTaiKhoan);
ALTER TABLE NhaPhatTrien ADD CONSTRAINT PK_NhaPhatTrien PRIMARY KEY (MaNPT);
ALTER TABLE NhaPhatTrien ADD CONSTRAINT UQ_NhaPhatTrien_TaiKhoan UNIQUE (MaTaiKhoan);
ALTER TABLE NhaPhatTrien ADD CONSTRAINT UQ_NhaPhatTrien_Email UNIQUE (Email);
ALTER TABLE NhaPhatTrien ADD CONSTRAINT CK_NhaPhatTrien_Loai CHECK (LoaiNPT IN ('Cá nhân', 'Studio', 'Doanh nghiệp'));
ALTER TABLE NhaPhatTrien ADD CONSTRAINT CK_NhaPhatTrien_TyLe CHECK (TyLeChiaSe BETWEEN 0 AND 1);
ALTER TABLE NhaPhatTrien ADD CONSTRAINT FK_NhaPhatTrien_TaiKhoan FOREIGN KEY (MaTaiKhoan) REFERENCES TaiKhoan(MaTaiKhoan);
ALTER TABLE NguoiChoi ADD CONSTRAINT PK_NguoiChoi PRIMARY KEY (MaNguoiChoi);
ALTER TABLE NguoiChoi ADD CONSTRAINT UQ_NguoiChoi_TaiKhoan UNIQUE (MaTaiKhoan);
ALTER TABLE NguoiChoi ADD CONSTRAINT UQ_NguoiChoi_Email UNIQUE (Email);
ALTER TABLE NguoiChoi ADD CONSTRAINT FK_NguoiChoi_TaiKhoan FOREIGN KEY (MaTaiKhoan) REFERENCES TaiKhoan(MaTaiKhoan);
ALTER TABLE TheLoai ADD CONSTRAINT PK_TheLoai PRIMARY KEY (MaTheLoai);
ALTER TABLE TheLoai ADD CONSTRAINT UQ_TheLoai_Ten UNIQUE (TenTheLoai);
ALTER TABLE Game ADD CONSTRAINT PK_Game PRIMARY KEY (MaGame);
ALTER TABLE Game ADD CONSTRAINT CK_Game_TrangThai CHECK (TrangThai IN ('Đang phát hành', 'Chưa phát hành', 'Đã gỡ bỏ'));
ALTER TABLE Game ADD CONSTRAINT CK_Game_Gia CHECK (GiaGoc >= 0);
ALTER TABLE Game ADD CONSTRAINT CK_Game_DoTuoi CHECK (DoTuoi >= 0);
ALTER TABLE Game ADD CONSTRAINT CK_Game_LuotMua CHECK (LuotMua >= 0);
ALTER TABLE Game ADD CONSTRAINT CK_Game_NgayPhatHanh CHECK (TrangThai <> 'Đang phát hành' OR NgayPhatHanh IS NOT NULL);
ALTER TABLE Game ADD CONSTRAINT FK_Game_NhaPhatTrien FOREIGN KEY (MaNPT) REFERENCES NhaPhatTrien(MaNPT);
ALTER TABLE GameMedia ADD CONSTRAINT PK_GameMedia PRIMARY KEY (MaMedia);
ALTER TABLE GameMedia ADD CONSTRAINT CK_GameMedia_Loai CHECK (LoaiMedia IN ('Ảnh bìa', 'Ảnh phụ', 'Video'));
ALTER TABLE GameMedia ADD CONSTRAINT FK_GameMedia_Game FOREIGN KEY (MaGame) REFERENCES Game(MaGame);
ALTER TABLE DanhMucTheLoai ADD CONSTRAINT PK_DanhMucTheLoai PRIMARY KEY (MaTheLoai, MaGame);
ALTER TABLE DanhMucTheLoai ADD CONSTRAINT FK_DanhMuc_TheLoai FOREIGN KEY (MaTheLoai) REFERENCES TheLoai(MaTheLoai);
ALTER TABLE DanhMucTheLoai ADD CONSTRAINT FK_DanhMuc_Game FOREIGN KEY (MaGame) REFERENCES Game(MaGame);
ALTER TABLE PhienBanGame ADD CONSTRAINT PK_PhienBanGame PRIMARY KEY (MaPhienBan);
ALTER TABLE PhienBanGame ADD CONSTRAINT UQ_PhienBan_Ten UNIQUE (MaGame, TenPhienBan);
ALTER TABLE PhienBanGame ADD CONSTRAINT CK_PhienBan_DungLuong CHECK (DungLuong > 0);
ALTER TABLE PhienBanGame ADD CONSTRAINT CK_PhienBan_TrangThai CHECK (TrangThai IN ('Đang phát hành', 'Chưa phát hành'));
ALTER TABLE PhienBanGame ADD CONSTRAINT FK_PhienBan_Game FOREIGN KEY (MaGame) REFERENCES Game(MaGame);
ALTER TABLE YeuCauPhatHanh ADD CONSTRAINT PK_YeuCauPhatHanh PRIMARY KEY (MaYeuCau);
ALTER TABLE YeuCauPhatHanh ADD CONSTRAINT CK_YCPH_TrangThai CHECK (TrangThai IN ('Chờ duyệt', 'Đã duyệt', 'Từ chối'));
ALTER TABLE YeuCauPhatHanh ADD CONSTRAINT CK_YCPH_LyDo CHECK (TrangThai <> 'Từ chối' OR LyDoTuChoi IS NOT NULL);
ALTER TABLE YeuCauPhatHanh ADD CONSTRAINT CK_YCPH_XuLy CHECK ( TrangThai = 'Chờ duyệt' OR (MaNVXuLy IS NOT NULL AND NgayXuLy IS NOT NULL) );
ALTER TABLE YeuCauPhatHanh ADD CONSTRAINT CK_YCPH_NgayXuLy CHECK (NgayXuLy IS NULL OR NgayXuLy >= NgayYeuCau);
ALTER TABLE YeuCauPhatHanh ADD CONSTRAINT FK_YCPH_NPT FOREIGN KEY (MaNPT) REFERENCES NhaPhatTrien(MaNPT);
ALTER TABLE YeuCauPhatHanh ADD CONSTRAINT FK_YCPH_Game FOREIGN KEY (MaGame) REFERENCES Game(MaGame);
ALTER TABLE YeuCauPhatHanh ADD CONSTRAINT FK_YCPH_PhienBan FOREIGN KEY (MaPhienBan) REFERENCES PhienBanGame(MaPhienBan);
ALTER TABLE YeuCauPhatHanh ADD CONSTRAINT FK_YCPH_NhanVien FOREIGN KEY (MaNVXuLy) REFERENCES NhanVien(MaNV);
ALTER TABLE Wishlist ADD CONSTRAINT PK_Wishlist PRIMARY KEY (MaNguoiChoi, MaGame);
ALTER TABLE Wishlist ADD CONSTRAINT FK_Wishlist_NguoiChoi FOREIGN KEY (MaNguoiChoi) REFERENCES NguoiChoi(MaNguoiChoi);
ALTER TABLE Wishlist ADD CONSTRAINT FK_Wishlist_Game FOREIGN KEY (MaGame) REFERENCES Game(MaGame);
ALTER TABLE GioHang ADD CONSTRAINT PK_GioHang PRIMARY KEY (MaNguoiChoi, MaGame);
ALTER TABLE GioHang ADD CONSTRAINT FK_GioHang_NguoiChoi FOREIGN KEY (MaNguoiChoi) REFERENCES NguoiChoi(MaNguoiChoi);
ALTER TABLE GioHang ADD CONSTRAINT FK_GioHang_Game FOREIGN KEY (MaGame) REFERENCES Game(MaGame);
ALTER TABLE MaGiamGia ADD CONSTRAINT PK_MaGiamGia PRIMARY KEY (MaMaGiamGia);
ALTER TABLE MaGiamGia ADD CONSTRAINT UQ_MaGiamGia_Code UNIQUE (Code);
ALTER TABLE MaGiamGia ADD CONSTRAINT CK_MaGiamGia_TrangThai CHECK (TrangThai IN ('Đang hiệu lực', 'Hết hiệu lực'));
ALTER TABLE MaGiamGia ADD CONSTRAINT CK_MaGiamGia_Ngay CHECK (NgayBatDau <= NgayHetHan);
ALTER TABLE MaGiamGia ADD CONSTRAINT CK_MaGiamGia_Luot CHECK (GioiHanSuDung >= 0 AND LuotDung >= 0 AND LuotDung <= GioiHanSuDung);
ALTER TABLE MaGiamGia ADD CONSTRAINT CK_MaGiamGia_Tien CHECK (SoTienGiam >= 0 AND TongGiaToiThieu >= 0);
ALTER TABLE GiaoDich ADD CONSTRAINT PK_GiaoDich PRIMARY KEY (MaGD);
ALTER TABLE GiaoDich ADD CONSTRAINT CK_GiaoDich_TrangThai CHECK (TrangThai IN ('Chờ thanh toán', 'Thành công', 'Thất bại'));
ALTER TABLE GiaoDich ADD CONSTRAINT CK_GiaoDich_Tien CHECK (TongTienGoc >= 0 AND TongGiamGia >= 0 AND TongThanhToan >= 0);
ALTER TABLE GiaoDich ADD CONSTRAINT FK_GiaoDich_NguoiChoi FOREIGN KEY (MaNguoiChoi) REFERENCES NguoiChoi(MaNguoiChoi);
ALTER TABLE GiaoDich ADD CONSTRAINT FK_GiaoDich_MaGiamGia FOREIGN KEY (MaMaGiamGia) REFERENCES MaGiamGia(MaMaGiamGia);
ALTER TABLE ChiTietGiaoDich ADD CONSTRAINT PK_ChiTietGiaoDich PRIMARY KEY (MaGD, MaGame);
ALTER TABLE ChiTietGiaoDich ADD CONSTRAINT CK_CTGD_Tien CHECK (GiaGoc >= 0 AND SoTienGiamKM >= 0 AND GiaBan >= 0);
ALTER TABLE ChiTietGiaoDich ADD CONSTRAINT CK_CTGD_GiaBan CHECK (GiaBan = GiaGoc - SoTienGiamKM);
ALTER TABLE ChiTietGiaoDich ADD CONSTRAINT FK_CTGD_GiaoDich FOREIGN KEY (MaGD) REFERENCES GiaoDich(MaGD);
ALTER TABLE ChiTietGiaoDich ADD CONSTRAINT FK_CTGD_Game FOREIGN KEY (MaGame) REFERENCES Game(MaGame);
ALTER TABLE SoHuuGame ADD CONSTRAINT PK_SoHuuGame PRIMARY KEY (MaNguoiChoi, MaGame);
ALTER TABLE SoHuuGame ADD CONSTRAINT CK_SoHuu_GioChoi CHECK (SoGioChoi >= 0);
ALTER TABLE SoHuuGame ADD CONSTRAINT FK_SoHuu_NguoiChoi FOREIGN KEY (MaNguoiChoi) REFERENCES NguoiChoi(MaNguoiChoi);
ALTER TABLE SoHuuGame ADD CONSTRAINT FK_SoHuu_Game FOREIGN KEY (MaGame) REFERENCES Game(MaGame);
ALTER TABLE SoHuuGame ADD CONSTRAINT FK_SoHuu_GiaoDich FOREIGN KEY (MaGD) REFERENCES GiaoDich(MaGD);
ALTER TABLE DanhGia ADD CONSTRAINT PK_DanhGia PRIMARY KEY (MaDanhGia);
ALTER TABLE DanhGia ADD CONSTRAINT UQ_DanhGia_NguoiChoi_Game UNIQUE (MaNguoiChoi, MaGame);
ALTER TABLE DanhGia ADD CONSTRAINT CK_DanhGia_Diem CHECK (DiemDanhGia BETWEEN 1 AND 5);
ALTER TABLE DanhGia ADD CONSTRAINT FK_DanhGia_Game FOREIGN KEY (MaGame) REFERENCES Game(MaGame);
ALTER TABLE DanhGia ADD CONSTRAINT FK_DanhGia_NguoiChoi FOREIGN KEY (MaNguoiChoi) REFERENCES NguoiChoi(MaNguoiChoi);
ALTER TABLE KhuyenMai ADD CONSTRAINT PK_KhuyenMai PRIMARY KEY (MaKM);
ALTER TABLE KhuyenMai ADD CONSTRAINT CK_KhuyenMai_TrangThai CHECK (TrangThai IN ('Đang hiệu lực', 'Hết hiệu lực'));
ALTER TABLE KhuyenMai ADD CONSTRAINT CK_KhuyenMai_Ngay CHECK (NgayBatDau <= NgayKetThuc);
ALTER TABLE ChiTietKhuyenMai ADD CONSTRAINT PK_ChiTietKhuyenMai PRIMARY KEY (MaKM, MaGame);
ALTER TABLE ChiTietKhuyenMai ADD CONSTRAINT CK_CTKM_PhanTram CHECK (PhanTramKM > 0 AND PhanTramKM <= 100);
ALTER TABLE ChiTietKhuyenMai ADD CONSTRAINT FK_CTKM_KhuyenMai FOREIGN KEY (MaKM) REFERENCES KhuyenMai(MaKM);
ALTER TABLE ChiTietKhuyenMai ADD CONSTRAINT FK_CTKM_Game FOREIGN KEY (MaGame) REFERENCES Game(MaGame);
ALTER TABLE Ticket ADD CONSTRAINT PK_Ticket PRIMARY KEY (MaTicket);
ALTER TABLE Ticket ADD CONSTRAINT CK_Ticket_TrangThai CHECK (TrangThai IN ('Chờ xử lý', 'Đang xử lý', 'Đã xử lý'));
ALTER TABLE Ticket ADD CONSTRAINT CK_Ticket_XuLy CHECK ( TrangThai <> 'Đã xử lý' OR (MaNVXuLy IS NOT NULL AND NoiDungPhanHoi IS NOT NULL AND NgayXuLy IS NOT NULL) );
ALTER TABLE Ticket ADD CONSTRAINT CK_Ticket_NgayXuLy CHECK (NgayXuLy IS NULL OR NgayXuLy >= NgayTao);
ALTER TABLE Ticket ADD CONSTRAINT FK_Ticket_NguoiChoi FOREIGN KEY (MaNguoiChoi) REFERENCES NguoiChoi(MaNguoiChoi);
ALTER TABLE Ticket ADD CONSTRAINT FK_Ticket_Game FOREIGN KEY (MaGame) REFERENCES Game(MaGame);
ALTER TABLE Ticket ADD CONSTRAINT FK_Ticket_GiaoDich FOREIGN KEY (MaGD) REFERENCES GiaoDich(MaGD);
ALTER TABLE Ticket ADD CONSTRAINT FK_Ticket_NhanVien FOREIGN KEY (MaNVXuLy) REFERENCES NhanVien(MaNV);




